idf_component_register(SRCS "AppMain.cpp"
                       INCLUDE_DIRS "."
                                "../build/config"
                                "../components/F7Services"
                                "../components/F7Services/WiFi"
                                "../components/F7Services/System"
                                "../components/F7Services/Messaging"
                                "../components/F7Services/MeshNetwork"
                                "../components/F7Services/Exceptions"
                                "../components/F7Services/Bluetooth"
                                "../components/F7Services/Bluetooth/rapidjson"
                                )
