ASM_SRC = 	asm/adddf3vfp.S asm/addsf3.S asm/addsf3vfp.S asm/aeabi_cdcmp.S asm/aeabi_cfcmp.S asm/aeabi_dcmp.S asm/aeabi_fcmp.S  \
		asm/aeabi_idivmod.S asm/aeabi_ldivmod.S asm/aeabi_memcmp.S asm/aeabi_memcpy.S asm/aeabi_memmove.S asm/aeabi_memset.S  \
		asm/aeabi_uidivmod.S asm/aeabi_uldivmod.S asm/bswapdi2.S asm/bswapsi2.S asm/chkstk.S asm/clzdi2.S asm/clzsi2.S  \
		asm/comparesf2.S asm/divdf3vfp.S asm/divmodsi4.S asm/divsf3vfp.S asm/divsi3.S asm/eqdf2vfp.S asm/eqsf2vfp.S  \
		asm/extendsfdf2vfp.S asm/fixdfsivfp.S asm/fixsfsivfp.S asm/fixunsdfsivfp.S asm/fixunssfsivfp.S asm/floatsidfvfp.S  \
		asm/floatsisfvfp.S asm/floatunssidfvfp.S asm/floatunssisfvfp.S asm/gedf2vfp.S asm/gesf2vfp.S asm/gtdf2vfp.S  \
		asm/gtsf2vfp.S asm/ledf2vfp.S asm/lesf2vfp.S asm/ltdf2vfp.S asm/ltsf2vfp.S asm/modsi3.S asm/muldf3vfp.S asm/mulsf3vfp.S  \
		asm/nedf2vfp.S asm/negdf2vfp.S asm/negsf2vfp.S asm/nesf2vfp.S asm/restore_vfp_d8_d15_regs.S asm/impure.S asm/sync.S \
		asm/save_vfp_d8_d15_regs.S asm/subdf3vfp.S asm/subsf3vfp.S asm/switch16.S asm/switch32.S asm/switch8.S asm/switchu8.S  \
		asm/sync_fetch_and_add_4.S asm/sync_fetch_and_add_8.S asm/sync_fetch_and_and_4.S asm/sync_fetch_and_and_8.S  \
		asm/sync_fetch_and_max_4.S asm/sync_fetch_and_max_8.S asm/sync_fetch_and_min_4.S asm/sync_fetch_and_min_8.S  \
		asm/sync_fetch_and_nand_4.S asm/sync_fetch_and_nand_8.S asm/sync_fetch_and_or_4.S asm/sync_fetch_and_or_8.S  \
		asm/sync_fetch_and_sub_4.S asm/sync_fetch_and_sub_8.S asm/sync_fetch_and_umax_4.S asm/sync_fetch_and_umax_8.S  \
		asm/sync_fetch_and_umin_4.S asm/sync_fetch_and_umin_8.S asm/sync_fetch_and_xor_4.S asm/sync_fetch_and_xor_8.S  \
		asm/truncdfsf2vfp.S asm/udivmodsi4.S asm/udivsi3.S asm/umodsi3.S asm/unorddf2vfp.S asm/unordsf2vfp.S \
		asm/aeabi_cdcmpeq_check_nan.c asm/aeabi_cfcmpeq_check_nan.c asm/aeabi_div0.c asm/aeabi_drsub.c asm/aeabi_frsub.c asm/fp_mode.c

COM_SRC = 	absvdi2.c absvsi2.c absvti2.c adddf3.c addtf3.c addvdi3.c addvsi3.c addvti3.c apple_versioning.c ashldi3.c \
		ashlti3.c ashrdi3.c ashrti3.c clzti2.c cmpdi2.c cmpti2.c comparedf2.c comparetf2.c cpu_model.c ctzdi2.c ctzsi2.c \
		ctzti2.c divdc3.c divdf3.c divdi3.c divmoddi4.c divsc3.c divsf3.c divtc3.c divtf3.c divti3.c \
		divxc3.c extenddftf2.c extendhfsf2.c extendsfdf2.c extendsftf2.c ffsdi2.c \
		ffssi2.c ffsti2.c fixdfdi.c fixdfsi.c fixdfti.c fixsfdi.c fixsfsi.c fixsfti.c fixtfdi.c fixtfsi.c fixtfti.c fixunsdfdi.c \
		fixunsdfsi.c fixunsdfti.c fixunssfdi.c fixunssfsi.c fixunssfti.c fixunstfdi.c fixunstfsi.c fixunstfti.c fixunsxfdi.c \
		fixunsxfsi.c fixunsxfti.c fixxfdi.c fixxfti.c floatdidf.c floatdisf.c floatditf.c floatdixf.c floatsidf.c floatsisf.c \
		floatsitf.c floattidf.c floattisf.c floattitf.c floattixf.c floatundidf.c floatundisf.c floatunditf.c floatundixf.c \
		floatunsidf.c floatunsisf.c floatunsitf.c floatuntidf.c floatuntisf.c floatuntitf.c floatuntixf.c \
		lshrdi3.c lshrti3.c mingw_fixfloat.c moddi3.c modti3.c muldc3.c muldf3.c \
		muldi3.c mulodi4.c mulosi4.c muloti4.c mulsc3.c mulsf3.c multc3.c multf3.c multi3.c mulvdi3.c mulvsi3.c mulvti3.c \
		mulxc3.c negdf2.c negdi2.c negsf2.c negti2.c negvdi2.c negvsi2.c negvti2.c os_version_check.c paritydi2.c paritysi2.c \
		parityti2.c popcountdi2.c popcountsi2.c popcountti2.c powidf2.c powisf2.c powitf2.c powixf2.c subdf3.c subsf3.c \
		subtf3.c subvdi3.c subvsi3.c subvti3.c trampoline_setup.c truncdfhf2.c truncdfsf2.c truncsfhf2.c trunctfdf2.c \
		trunctfsf2.c ucmpdi2.c ucmpti2.c udivdi3.c udivmoddi4.c udivmodti4.c udivti3.c umoddi3.c \
		umodti3.c sync_synchronize.c unwind.c

OBJS = 		adddf3vfp.o addsf3.o addsf3vfp.o aeabi_cdcmpeq_check_nan.o aeabi_cdcmp.o \
		aeabi_cfcmpeq_check_nan.o aeabi_cfcmp.o aeabi_dcmp.o aeabi_div0.o aeabi_drsub.o \
		aeabi_fcmp.o aeabi_frsub.o aeabi_idivmod.o aeabi_ldivmod.o aeabi_memcmp.o aeabi_memcpy.o \
		aeabi_memmove.o aeabi_memset.o aeabi_uidivmod.o aeabi_uldivmod.o bswapdi2.o bswapsi2.o \
		chkstk.o clzdi2.o clzsi2.o comparesf2.o divdf3vfp.o divmodsi4.o divsf3vfp.o divsi3.o \
		eqdf2vfp.o eqsf2vfp.o extendsfdf2vfp.o fixdfsivfp.o fixsfsivfp.o fixunsdfsivfp.o fixunssfsivfp.o \
		floatsidfvfp.o floatsisfvfp.o floatunssidfvfp.o floatunssisfvfp.o fp_mode.o gedf2vfp.o gesf2vfp.o \
		gtdf2vfp.o gtsf2vfp.o ledf2vfp.o lesf2vfp.o ltdf2vfp.o ltsf2vfp.o modsi3.o muldf3vfp.o \
		mulsf3vfp.o nedf2vfp.o negdf2vfp.o negsf2vfp.o nesf2vfp.o restore_vfp_d8_d15_regs.o \
		save_vfp_d8_d15_regs.o subdf3vfp.o subsf3vfp.o switch16.o switch32.o switch8.o switchu8.o \
		sync_fetch_and_add_4.o sync_fetch_and_add_8.o sync_fetch_and_and_4.o sync_fetch_and_and_8.o \
		sync_fetch_and_max_4.o sync_fetch_and_max_8.o sync_fetch_and_min_4.o sync_fetch_and_min_8.o \
		sync_fetch_and_nand_4.o sync_fetch_and_nand_8.o sync_fetch_and_or_4.o sync_fetch_and_or_8.o \
		sync_fetch_and_sub_4.o sync_fetch_and_sub_8.o sync_fetch_and_umax_4.o sync_fetch_and_umax_8.o \
		sync_fetch_and_umin_4.o sync_fetch_and_umin_8.o sync_fetch_and_xor_4.o sync_fetch_and_xor_8.o \
		sync_synchronize.o truncdfsf2vfp.o udivmodsi4.o udivsi3.o umodsi3.o unorddf2vfp.o unordsf2vfp.o \
		absvdi2.o absvsi2.o absvti2.o adddf3.o addtf3.o addvdi3.o addvsi3.o addvti3.o apple_versioning.o ashldi3.o \
		ashlti3.o ashrdi3.o ashrti3.o clzti2.o cmpdi2.o cmpti2.o comparedf2.o comparetf2.o cpu_model.o ctzdi2.o ctzsi2.o \
		ctzti2.o divdc3.o divdf3.o divdi3.o divmoddi4.o divsc3.o divsf3.o divtc3.o divtf3.o divti3.o \
		divxc3.o extenddftf2.o extendhfsf2.o extendsfdf2.o extendsftf2.o ffsdi2.o \
		ffssi2.o ffsti2.o fixdfdi.o fixdfsi.o fixdfti.o fixsfdi.o fixsfsi.o fixsfti.o fixtfdi.o fixtfsi.o fixtfti.o fixunsdfdi.o \
		fixunsdfsi.o fixunsdfti.o fixunssfdi.o fixunssfsi.o fixunssfti.o fixunstfdi.o fixunstfsi.o fixunstfti.o fixunsxfdi.o \
		fixunsxfsi.o fixunsxfti.o fixxfdi.o fixxfti.o floatdidf.o floatdisf.o floatditf.o floatdixf.o floatsidf.o floatsisf.o \
		floatsitf.o floattidf.o floattisf.o floattitf.o floattixf.o floatundidf.o floatundisf.o floatunditf.o floatundixf.o \
		floatunsidf.o floatunsisf.o floatunsitf.o floatuntidf.o floatuntisf.o floatuntitf.o floatuntixf.o impure.o \
		lshrdi3.o lshrti3.o mingw_fixfloat.o moddi3.o modti3.o muldc3.o muldf3.o sync.o \
		muldi3.o mulodi4.o mulosi4.o muloti4.o mulsc3.o mulsf3.o multc3.o multf3.o multi3.o mulvdi3.o mulvsi3.o mulvti3.o \
		mulxc3.o negdf2.o negdi2.o negsf2.o negti2.o negvdi2.o negvsi2.o negvti2.o os_version_check.o paritydi2.o paritysi2.o \
		parityti2.o popcountdi2.o popcountsi2.o popcountti2.o powidf2.o powisf2.o powitf2.o powixf2.o subdf3.o subsf3.o \
		subtf3.o subvdi3.o subvsi3.o subvti3.o trampoline_setup.o truncdfhf2.o truncdfsf2.o truncsfhf2.o trunctfdf2.o \
		trunctfsf2.o ucmpdi2.o ucmpti2.o udivdi3.o udivmoddi4.o udivmodti4.o udivti3.o umoddi3.o umodti3.o unwind.o

all:		libbuiltin.a

clean:
		rm -f $(OBJS) libbuiltin.a

libbuiltin.a: 	$(OBJS)
		arm-none-eabi-ar -r $@ $^ 

$(OBJS):	$(ASM_SRC) $(COM_SRC)
		clang --target=thumb2-none-eabi -mfloat-abi=hard -mfpu=fpv5-d16 -mthumb -mcpu=cortex-m7 -mfloat-abi=hard -mfpu=fpv5-d16 -fpic -fshort-enums -meabi gnu -c $?
		# clang --target=armv7-nono-eabi -mhard-float -fpic -mthumb -c $?

