/*
 *      espcp_encoders.h
 *
 *      Message encoders and decoders.
 *
 *      *************************** WARNING ***************************
 *
 *      THIS FILE IS AUTOMATICALLY GENERATED.  DO NOT EDIT THIS FILE AS
 *      CHANGES WILL BE OVERWRITTEN.
 *
 *      *************************** WARNING ***************************
 */

#ifndef _ESPCP_ENCODERS_H
#define _ESPCP_ENCODERS_H

#include <stdlib.h>
#include <string.h>
#include "espcp_shared_enums.h"
#include "espcp_message.h"

struct espcp_system_configuration_s
{
    uint8_t maximum_message_queue_length;
    int32_t maximum_retry_count;
    uint8_t antenna;
    uint8_t board_mac_address[6];
    uint8_t soft_ap_mac_address[6];
    uint8_t bluetooth_mac_address[6];
    char * device_name;
    char * default_access_point;
    uint8_t reset_reason;
    uint32_t version_major;
    uint32_t version_minor;
    uint32_t version_revision;
    uint32_t version_build;
    uint8_t build_day;
    uint8_t build_month;
    uint8_t build_year;
    uint8_t build_hour;
    uint8_t build_minute;
    uint8_t build_second;
    uint32_t build_hash;
    char * build_branch_name;
};
typedef struct espcp_system_configuration_s espcp_system_configuration_t;

struct espcp_configuration_value_s
{
    uint32_t item;
    uint32_t value_length;
    uint8_t *value;
};
typedef struct espcp_configuration_value_s espcp_configuration_value_t;

struct espcp_error_event_s
{
    uint32_t error_code;
    uint8_t interface;
    uint32_t error_data_length;
    uint8_t *error_data;
};
typedef struct espcp_error_event_s espcp_error_event_t;

struct espcp_access_point_information_s
{
    char * network_name;
    char * password;
    uint32_t ip_address;
    uint32_t subnet_mask;
    uint32_t gateway;
    uint8_t wi_fi_authentication_mode;
    uint8_t channel;
    uint8_t hidden;
};
typedef struct espcp_access_point_information_s espcp_access_point_information_t;

struct espcp_disconnect_from_access_point_request_s
{
    uint8_t turn_off_wi_fi_interface;
};
typedef struct espcp_disconnect_from_access_point_request_s espcp_disconnect_from_access_point_request_t;

struct espcp_connect_event_data_s
{
    uint32_t ip_address;
    uint32_t subnet_mask;
    uint32_t gateway;
    char ssid[33];
    uint8_t bssid[6];
    uint8_t channel;
    uint8_t authentication_mode;
    uint32_t reason;
};
typedef struct espcp_connect_event_data_s espcp_connect_event_data_t;

struct espcp_got_ip_event_data_s
{
    uint32_t dns_address;
};
typedef struct espcp_got_ip_event_data_s espcp_got_ip_event_data_t;

struct espcp_node_connection_change_event_data_s
{
    uint32_t ip_address;
    uint8_t mac_address[6];
};
typedef struct espcp_node_connection_change_event_data_s espcp_node_connection_change_event_data_t;

struct espcp_disconnect_event_data_s
{
    uint8_t retrying;
    int32_t retries_remaining;
    uint32_t reason;
};
typedef struct espcp_disconnect_event_data_s espcp_disconnect_event_data_t;

struct espcp_access_point_s
{
    char ssid[33];
    uint8_t bssid[6];
    uint8_t primary_channel;
    uint8_t secondary_channel;
    int8_t rssi;
    uint8_t authentication_mode;
    uint32_t protocols;
};
typedef struct espcp_access_point_s espcp_access_point_t;

struct espcp_access_point_list_s
{
    uint32_t number_of_access_points;
    uint32_t access_points_length;
    uint8_t *access_points;
};
typedef struct espcp_access_point_list_s espcp_access_point_list_t;

struct espcp_sock_addr_s
{
    uint8_t family;
    uint16_t port;
    uint32_t ip4_address;
    uint32_t flow_info;
    uint8_t ip6_address[16];
    uint32_t scope_i_d;
};
typedef struct espcp_sock_addr_s espcp_sock_addr_t;

struct espcp_addr_info_s
{
    uint32_t my_heap_address;
    int32_t flags;
    int32_t family;
    int32_t socket_type;
    int32_t protocol;
    uint32_t addr_len;
    uint32_t addr_length;
    uint8_t *addr;
    char * canon_name;
    void *next;
};
typedef struct espcp_addr_info_s espcp_addr_info_t;

struct espcp_get_addr_info_request_s
{
    char * node_name;
    char * serv_name;
    uint32_t hints_length;
    uint8_t *hints;
};
typedef struct espcp_get_addr_info_request_s espcp_get_addr_info_request_t;

struct espcp_get_addr_info_response_s
{
    int32_t addr_info_response_errno;
    uint32_t res_length;
    uint8_t *res;
};
typedef struct espcp_get_addr_info_response_s espcp_get_addr_info_response_t;

struct espcp_socket_request_s
{
    void *address_information;
    int32_t domain;
    int32_t type;
    int32_t protocol;
};
typedef struct espcp_socket_request_s espcp_socket_request_t;

struct espcp_integer_response_s
{
    int32_t result;
};
typedef struct espcp_integer_response_s espcp_integer_response_t;

struct espcp_integer_and_errno_response_s
{
    int32_t result;
    int32_t response_errno;
};
typedef struct espcp_integer_and_errno_response_s espcp_integer_and_errno_response_t;

struct espcp_connect_request_s
{
    int32_t socket_handle;
    uint32_t addr_length;
    uint8_t *addr;
};
typedef struct espcp_connect_request_s espcp_connect_request_t;

struct espcp_free_addr_info_request_s
{
    uint32_t addr_info_address;
};
typedef struct espcp_free_addr_info_request_s espcp_free_addr_info_request_t;

struct espcp_time_val_s
{
    uint32_t tv_sec;
    uint32_t tv_usec;
};
typedef struct espcp_time_val_s espcp_time_val_t;

struct espcp_set_sock_opt_request_s
{
    int32_t socket_handle;
    int32_t level;
    int32_t option_name;
    uint32_t option_value_length;
    uint8_t *option_value;
    int32_t option_len;
};
typedef struct espcp_set_sock_opt_request_s espcp_set_sock_opt_request_t;

struct espcp_get_sock_opt_request_s
{
    int32_t socket_handle;
    int32_t level;
    int32_t option_name;
};
typedef struct espcp_get_sock_opt_request_s espcp_get_sock_opt_request_t;

struct espcp_get_sock_opt_response_s
{
    int32_t result;
    int32_t response_errno;
    uint32_t option_value_length;
    uint8_t *option_value;
    int32_t option_len;
};
typedef struct espcp_get_sock_opt_response_s espcp_get_sock_opt_response_t;

struct espcp_linger_s
{
    int32_t l_on_off;
    int32_t l_linger;
};
typedef struct espcp_linger_s espcp_linger_t;

struct espcp_write_request_s
{
    int32_t socket_handle;
    uint32_t buffer_length;
    uint8_t *buffer;
    int32_t count;
};
typedef struct espcp_write_request_s espcp_write_request_t;

struct espcp_read_request_s
{
    int32_t socket_handle;
    int32_t count;
};
typedef struct espcp_read_request_s espcp_read_request_t;

struct espcp_read_response_s
{
    uint32_t buffer_length;
    uint8_t *buffer;
    int32_t read_response_result;
    int32_t read_response_errno;
};
typedef struct espcp_read_response_s espcp_read_response_t;

struct espcp_close_request_s
{
    int32_t socket_handle;
};
typedef struct espcp_close_request_s espcp_close_request_t;

struct espcp_get_battery_charge_level_response_s
{
    uint32_t level;
};
typedef struct espcp_get_battery_charge_level_response_s espcp_get_battery_charge_level_response_t;

// struct espcp_send_request_s
// {
//     int32_t socket_handle;
//     uint32_t buffer_length;
//     uint8_t *buffer;
//     int32_t length;
//     int32_t flags;
// };
// typedef struct espcp_send_request_s espcp_send_request_t;

struct espcp_send_to_request_s
{
    int32_t socket_handle;
    uint32_t buffer_length;
    uint8_t *buffer;
    int32_t length;
    int32_t flags;
    uint32_t destination_address_length;
    uint8_t *destination_address;
};
typedef struct espcp_send_to_request_s espcp_send_to_request_t;

struct espcp_recv_from_request_s
{
    int32_t socket_handle;
    int32_t length;
    int32_t flags;
    int32_t get_source_address;
};
typedef struct espcp_recv_from_request_s espcp_recv_from_request_t;

struct espcp_recv_from_response_s
{
    uint32_t buffer_length;
    uint8_t *buffer;
    int32_t result;
    int32_t response_errno;
    uint32_t source_address_length;
    uint8_t *source_address;
    uint32_t source_address_len;
};
typedef struct espcp_recv_from_response_s espcp_recv_from_response_t;

struct espcp_poll_request_s
{
    int32_t socket_handle;
    uint16_t events;
    int32_t timeout;
    int32_t setup;
    uint32_t setup_message_id;
};
typedef struct espcp_poll_request_s espcp_poll_request_t;

struct espcp_poll_response_s
{
    uint16_t returned_events;
    int32_t result;
    int32_t response_errno;
};
typedef struct espcp_poll_response_s espcp_poll_response_t;

struct espcp_interrupt_poll_response_s
{
    int32_t socket_handle;
    int32_t result;
    int32_t response_errno;
    uint16_t returned_events;
    uint32_t setup_message_id;
};
typedef struct espcp_interrupt_poll_response_s espcp_interrupt_poll_response_t;

struct espcp_listen_request_s
{
    int32_t socket_handle;
    int32_t back_log;
};
typedef struct espcp_listen_request_s espcp_listen_request_t;

struct espcp_bind_request_s
{
    int32_t socket_handle;
    uint32_t addr_length;
    uint8_t *addr;
};
typedef struct espcp_bind_request_s espcp_bind_request_t;

struct espcp_accept_request_s
{
    int32_t socket_handle;
};
typedef struct espcp_accept_request_s espcp_accept_request_t;

struct espcp_accept_response_s
{
    uint32_t addr_length;
    uint8_t *addr;
    int32_t result;
    int32_t response_errno;
};
typedef struct espcp_accept_response_s espcp_accept_response_t;

struct espcp_ioctl_request_s
{
    int32_t command;
};
typedef struct espcp_ioctl_request_s espcp_ioctl_request_t;

struct espcp_ioctl_response_s
{
    uint32_t addr_length;
    uint8_t *addr;
    int32_t flags;
    int32_t result;
    int32_t response_errno;
};
typedef struct espcp_ioctl_response_s espcp_ioctl_response_t;

struct espcp_get_sock_peer_name_request_s
{
    int32_t socket_handle;
};
typedef struct espcp_get_sock_peer_name_request_s espcp_get_sock_peer_name_request_t;

struct espcp_get_sock_peer_name_response_s
{
    uint32_t addr_length;
    uint8_t *addr;
    int32_t result;
    int32_t response_errno;
};
typedef struct espcp_get_sock_peer_name_response_s espcp_get_sock_peer_name_response_t;

struct espcp_event_data_s
{
    uint8_t interface;
    uint32_t function;
    uint32_t status_code;
    uint32_t message_id;
};
typedef struct espcp_event_data_s espcp_event_data_t;

struct espcp_event_data_payload_s
{
    uint32_t message_id;
    uint32_t payload_length;
    uint8_t *payload;
};
typedef struct espcp_event_data_payload_s espcp_event_data_payload_t;

struct espcp_set_antenna_request_s
{
    uint8_t antenna;
    uint8_t persist;
};
typedef struct espcp_set_antenna_request_s espcp_set_antenna_request_t;

struct espcp_b_t_stack_config_s
{
    char * config;
};
typedef struct espcp_b_t_stack_config_s espcp_b_t_stack_config_t;

struct espcp_b_t_data_write_request_s
{
    uint16_t handle;
    uint32_t data_length;
    uint8_t *data;
};
typedef struct espcp_b_t_data_write_request_s espcp_b_t_data_write_request_t;

struct espcp_b_t_get_handles_response_s
{
    uint16_t handle_count;
    uint32_t handles_length;
    uint8_t *handles;
};
typedef struct espcp_b_t_get_handles_response_s espcp_b_t_get_handles_response_t;

struct espcp_b_t_server_data_set_s
{
    uint16_t handle;
    uint32_t set_data_length;
    uint8_t *set_data;
};
typedef struct espcp_b_t_server_data_set_s espcp_b_t_server_data_set_t;

struct espcp_file_details_s
{
    char * name;
    uint16_t length;
};
typedef struct espcp_file_details_s espcp_file_details_t;

struct espcp_file_name_and_contents_s
{
    char * name;
    uint32_t contents_length;
    uint8_t *contents;
};
typedef struct espcp_file_name_and_contents_s espcp_file_name_and_contents_t;

struct espcp_file_name_list_s
{
    uint16_t number_of_files;
    uint32_t file_details_length;
    uint8_t *file_details;
};
typedef struct espcp_file_name_list_s espcp_file_name_list_t;

/**
 * @brief Logging configuration message data.
 */
struct espcp_logging_configuration_s
{
    /**
     * @brief Where should the log information go?
     */
    uint8_t interface;

    /**
     * @brief Which port should be used if UDP logging is to be used.
     */
    uint16_t udp_port;

    /**
     * @brief Which components should we log?
     */
    char *components_to_log;
};
typedef struct espcp_logging_configuration_s espcp_logging_configuration_t;

/**
 * @brief A message to send to the logging system.
 */
struct espcp_log_message_s
{
    /**
     * @brief Log level for this message.
     */
    uint8_t level;

    /**
     * @brief Message to send to the logging destination.
     */
    char *message;
};
typedef struct espcp_log_message_s espcp_log_message_t;

/*
 *      Encoding methods for the ESP32 SPI communications layer.
 *
 *      Functionality includes:
 *          - Encoding 16 / 32 bit values into buffers.
 *          - extract_ing 16 / 32 bit values from buffer.
 *          - CRC calculations.
 */

/*
 *      Seed for the 32-bit CRC calculation.
 */
#define ESPCP_CRC32_SEED 0xffffffff

uint32_t espcp_calculate_spi_buffer_size(uint32_t);
uint32_t espcp_encoded_packet_size(espcp_message_t *, bool);
uint16_t espcp_extract_uint16(uint8_t *);
void espcp_encode_uint16(uint16_t, uint8_t *);
uint32_t espcp_extract_uint32(uint8_t *);
void espcp_encode_uint32(uint32_t, uint8_t *);
int32_t espcp_extract_int32(uint8_t *);
void espcp_encode_int32(int32_t, uint8_t *);
char *espcp_extract_string(uint8_t *);
void espcp_encode_string(char *, uint8_t *);
uint32_t espcp_string_length(char *);
uint8_t espcp_crc8(const uint8_t *, uint16_t);
uint32_t espcp_crc32(const uint8_t *, uint16_t);
uint32_t espcp_progressive_crc32(uint32_t, uint8_t);
espcp_message_t *espcp_extract_message(uint8_t *, uint32_t, bool);
void espcp_encode_message(espcp_message_t *, uint8_t *, uint32_t *, bool);
uint32_t espcp_message_buffer_size(espcp_message_t *, bool);
espcp_system_configuration_t *espcp_extract_system_configuration(uint8_t *);
void espcp_encode_configuration_value(espcp_configuration_value_t *, uint8_t *);
int espcp_configuration_value_buffer_size(espcp_configuration_value_t *);
espcp_configuration_value_t *espcp_extract_configuration_value(uint8_t *);
espcp_error_event_t *espcp_extract_error_event(uint8_t *);
espcp_access_point_information_t *espcp_extract_access_point_information(uint8_t *);
void espcp_encode_connect_event_data(espcp_connect_event_data_t *, uint8_t *);
int espcp_connect_event_data_buffer_size(espcp_connect_event_data_t *);
espcp_connect_event_data_t *espcp_extract_connect_event_data(uint8_t *);
espcp_node_connection_change_event_data_t *espcp_extract_node_connection_change_event_data(uint8_t *);
espcp_disconnect_event_data_t *espcp_extract_disconnect_event_data(uint8_t *);
espcp_access_point_t *espcp_extract_access_point(uint8_t *);
espcp_access_point_list_t *espcp_extract_access_point_list(uint8_t *);
void espcp_encode_sock_addr(espcp_sock_addr_t *, uint8_t *);
int espcp_sock_addr_buffer_size(espcp_sock_addr_t *);
espcp_sock_addr_t *espcp_extract_sock_addr(uint8_t *);
espcp_addr_info_t *espcp_extract_addr_info(uint8_t *);
void espcp_encode_get_addr_info_request(espcp_get_addr_info_request_t *, uint8_t *);
int espcp_get_addr_info_request_buffer_size(espcp_get_addr_info_request_t *);
espcp_get_addr_info_response_t *espcp_extract_get_addr_info_response(uint8_t *);
void espcp_encode_socket_request(espcp_socket_request_t *, uint8_t *);
int espcp_socket_request_buffer_size(espcp_socket_request_t *);
espcp_integer_response_t *espcp_extract_integer_response(uint8_t *);
espcp_integer_and_errno_response_t *espcp_extract_integer_and_errno_response(uint8_t *);
void espcp_encode_connect_request(espcp_connect_request_t *, uint8_t *);
int espcp_connect_request_buffer_size(espcp_connect_request_t *);
void espcp_encode_free_addr_info_request(espcp_free_addr_info_request_t *, uint8_t *);
int espcp_free_addr_info_request_buffer_size(espcp_free_addr_info_request_t *);
void espcp_encode_time_val(espcp_time_val_t *, uint8_t *);
int espcp_time_val_buffer_size(espcp_time_val_t *);
espcp_time_val_t *espcp_extract_time_val(uint8_t *);
void espcp_encode_set_sock_opt_request(espcp_set_sock_opt_request_t *, uint8_t *);
int espcp_set_sock_opt_request_buffer_size(espcp_set_sock_opt_request_t *);
void espcp_encode_get_sock_opt_request(espcp_get_sock_opt_request_t *, uint8_t *);
int espcp_get_sock_opt_request_buffer_size(espcp_get_sock_opt_request_t *);
espcp_get_sock_opt_response_t *espcp_extract_get_sock_opt_response(uint8_t *);
void espcp_encode_linger(espcp_linger_t *, uint8_t *);
int espcp_linger_buffer_size(espcp_linger_t *);
espcp_linger_t *espcp_extract_linger(uint8_t *);
void espcp_encode_write_request(espcp_write_request_t *, uint8_t *);
int espcp_write_request_buffer_size(espcp_write_request_t *);
void espcp_encode_read_request(espcp_read_request_t *, uint8_t *);
int espcp_read_request_buffer_size(espcp_read_request_t *);
espcp_read_response_t *espcp_extract_read_response(uint8_t *);
void espcp_encode_close_request(espcp_close_request_t *, uint8_t *);
int espcp_close_request_buffer_size(espcp_close_request_t *);
espcp_get_battery_charge_level_response_t *espcp_extract_get_battery_charge_level_response(uint8_t *);
void espcp_encode_send_to_request(espcp_send_to_request_t *, uint8_t *);
int espcp_send_to_request_buffer_size(espcp_send_to_request_t *);
void espcp_encode_recv_from_request(espcp_recv_from_request_t *, uint8_t *);
int espcp_recv_from_request_buffer_size(espcp_recv_from_request_t *);
espcp_recv_from_response_t *espcp_extract_recv_from_response(uint8_t *);
void espcp_encode_poll_request(espcp_poll_request_t *, uint8_t *);
int espcp_poll_request_buffer_size(espcp_poll_request_t *);
espcp_poll_response_t *espcp_extract_poll_response(uint8_t *);
espcp_interrupt_poll_response_t *espcp_extract_interrupt_poll_response(uint8_t *);
void espcp_encode_listen_request(espcp_listen_request_t *, uint8_t *);
int espcp_listen_request_buffer_size(espcp_listen_request_t *);
void espcp_encode_bind_request(espcp_bind_request_t *, uint8_t *);
int espcp_bind_request_buffer_size(espcp_bind_request_t *);
void espcp_encode_accept_request(espcp_accept_request_t *, uint8_t *);
int espcp_accept_request_buffer_size(espcp_accept_request_t *);
espcp_accept_response_t *espcp_extract_accept_response(uint8_t *);
void espcp_encode_ioctl_request(espcp_ioctl_request_t *, uint8_t *);
int espcp_ioctl_request_buffer_size(espcp_ioctl_request_t *);
espcp_ioctl_response_t *espcp_extract_ioctl_response(uint8_t *);
void espcp_encode_get_sock_peer_name_request(espcp_get_sock_peer_name_request_t *, uint8_t *);
int espcp_get_sock_peer_name_request_buffer_size(espcp_get_sock_peer_name_request_t *);
espcp_get_sock_peer_name_response_t *espcp_extract_get_sock_peer_name_response(uint8_t *);
void espcp_encode_event_data(espcp_event_data_t *, uint8_t *);
int espcp_event_data_buffer_size(espcp_event_data_t *);
espcp_event_data_t *espcp_extract_event_data(uint8_t *);
espcp_event_data_payload_t *espcp_extract_event_data_payload(uint8_t *);
void espcp_encode_file_details(espcp_file_details_t *, uint8_t *);
int espcp_file_details_buffer_size(espcp_file_details_t *);
espcp_file_details_t *espcp_extract_file_details(uint8_t *);
void espcp_encode_file_name_and_contents(espcp_file_name_and_contents_t *, uint8_t *);
int espcp_file_name_and_contents_buffer_size(espcp_file_name_and_contents_t *);
espcp_file_name_and_contents_t *espcp_extract_file_name_and_contents(uint8_t *);
void espcp_encode_file_name_list(espcp_file_name_list_t *, uint8_t *);
int espcp_file_name_list_buffer_size(espcp_file_name_list_t *);
espcp_file_name_list_t *espcp_extract_file_name_list(uint8_t *);
int espcp_encoded_logging_configuration_buffer_size(espcp_logging_configuration_t *);
void espcp_encode_logging_configuration(espcp_logging_configuration_t *, uint8_t *);
int espcp_encoded_log_message_buffer_size(espcp_log_message_t *);
void espcp_encode_log_message(espcp_log_message_t *, uint8_t *);
espcp_got_ip_event_data_t *espcp_extract_got_ip_event_data(uint8_t *);
cell_event_data_t *espcp_extract_cell_event_data(uint8_t *buffer);
#endif /* _ESPCP_ENCODERS_H */
