/****************************************************************************
 * /include/meadow/meadow_thread_config.h
 * 
 *  Copyright (C) 2021-2022 Wilderness Labs. All rights reserved.
 *  Author:  Wilderness Labs
 * 
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name NuttX nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/
#ifndef __MEADOW_THREAD_CONFIG_H
#define __MEADOW_THREAD_CONFIG_H

#include <nuttx/config.h>

/**
 * This file contains the definitions for the threads as used by Meadow OS.  It
 * contains the defintions of the following parameters:
 * 
 *      1. Thread priority
 *      2. Thread name)
 *      3. Thread stack size
 * 
 * The thread name is only used by kthreads at the moment but is provided for all
 * threads for reference and future use.
 * 
 * This file has been put together to make it easier to change the properties of
 * any single thread in context with the other threads in the system.
 * 
 * It is important that each group of properties for a thread includes the reasoning
 * behind the priority and stack size values in order to guide future changes.
 * 
 * The thread information below is presented in priority order with the highest at
 * the top and the lowest at the bottom.  Please preserve this order when adding
 * new entries.
 */

/**
 * HCOM is the main communication thread for the Meadow OS.  It is responsible for
 * starting many of the other threads in the system.  It also supervises communication
 * with the host computer.  As such it should have a high priority.
 */
#define HCOM_THREAD_PRIORITY_HCOM_RECEIVE 180
#define HCOM_THREAD_NAME_HCOM_RECEIVE "HcomRecv"
#define HCOM_THREAD_STACKSIZE_HCOM_RECEIVE 2048

/**
 * Testing showed with priority of Process being higher than Receive there
 * were very rare download errors. This is probably in hcom_host_enq_deq.c.
 * With equal priority no errors have been detected.
 * I believe there is room for improvement in hcom_host_enq_deq.c.
 * 
 * Stack size is set by CONFIG_USERMAIN_STACKSIZE.
 */
#define HCOM_THREAD_PRIORITY_HCOM_PROCESS 180
#define HCOM_THREAD_NAME_HCOM_PROCESS "HcomProc"
#define HCOM_THREAD_STACKSIZE_HCOM_PROCESS CONFIG_USERMAIN_STACKSIZE

/**
 * The ESPCP thread is responsible for managing the communication between the STM32
 * main processor and the ESP32 coprocessor.  As such it should be considered to be
 * a hardware driver as the ESP32 is providing network communication for the STM32.
 * 
 * Note that the value for the thread priority is set slightly above the ESP32 event
 * handler thread.  The event handler thread needs communication to have completed
 * before it will have any data to process.
 */
#define ESPCP_THREAD_PRIORITY 171
#define ESPCP_THREAD_NAME "EspcpMainThread"
#define ESPCP_THREAD_STACKSIZE 4096

/**
 * The ESPCP event handler thread is responsible for processing the events that are
 * generated by the ESP32 coprocessor.  These events are mainly for Meadow.Core but
 * there are a few events which will impact the OS (network disconnect etc).
 * 
 * This thread relies upon data being made available through the main ESPCP thread.
 */
#define ESPCP_EVENT_HANDLER_THREAD_PRIORITY 170
#define ESPCP_EVENT_HANDLER_THREAD_NAME "EspcpEventHandler"
#define ESPCP_EVENT_HANDLER_THREAD_STACKSIZE 4096

/**
 * Insure HCOM recv thread runs before ESP32 recv, which is only used to program the
 * ESP32 from HCOM. Here this thread's priority is boosted ahead of most of the HCOM 
 * threads.
 */
#define HCOM_THREAD_PRIORITY_ESP32_RECEIVE 130
#define HCOM_THREAD_NAME_ESP32_RECEIVE "EspRecv"
#define HCOM_THREAD_STACKSIZE_ESP32_RECEIVE 2048

/**
 * The ramlog is part of nuttx and contains the syslog text
 */
#define HCOM_THREAD_PRIORITY_TRACE_RAMLOG 120
#define HCOM_THREAD_NAME_TRACE_RAMLOG "RamlogRead"
#define HCOM_THREAD_STACKSIZE_TRACE_RAMLOG 2048

/**
 * This thread reads stdout and forwards to the Host
 */
#define HCOM_THREAD_PRIORITY_STDERR_REDIRECT 120
#define HCOM_THREAD_NAME_STDOUT_REDIRECT "MonoOut"
#define HCOM_THREAD_STACKSIZE_STDOUT_REDIRECT 2048

/**
 * This thread reads stderr and forwards to the Host
 * 
 */
#define HCOM_THREAD_PRIORITY_STDOUT_REDIRECT 120
#define HCOM_THREAD_NAME_STDERR_REDIRECT "MonoErr"
#define HCOM_THREAD_STACKSIZE_STDERR_REDIRECT 2048

/**
 * This thread is used for remote debugging mono apps
 */
#define HCOM_THREAD_PRIORITY_REMOTE_DBG 120
#define HCOM_THREAD_NAME_REMOTE_DBG "RemoteDbg"
#define HCOM_THREAD_STACKSIZE_REMOTE_DBG 2048

#define HCOM_THREAD_PRIORITY_CLI_TRANSPORT 120
#define HCOM_THREAD_NAME_CLI_TRANSPORT "CliXport"
#define HCOM_THREAD_STACKSIZE_CLI_TRANSPORT 2048

#define HCOM_THREAD_PRIORITY_HOST_TRANSPORT 120
#define HCOM_THREAD_NAME_HOST_TRANSPORT "HostXport"
#define HCOM_THREAD_STACKSIZE_HOST_TRANSPORT 2048

/**
 * This task runs the mono runtime system and any threads created as part of
 * application execution.  Note that threads launched by Mono will also run at
 * this priority.  This has the effect of putting in a round-robin scheduling
 * pattern.  Care should be taken when creating any other threads at this priority
 * as they will be impacted by the number of threads created by mono and the user
 * application.
 */
#define MONO_TASK_PRIORITY 100
#define MONO_TASK_NAME "Mono"
#define MONO_TASK_STACKSIZE CONFIG_PTHREAD_STACK_DEFAULT

#endif // __MEADOW_THREAD_CONFIG_H