/*
 *      espcp_encoders.h
 *
 *      Message encoders and decoders.
 *
 *      *************************** WARNING ***************************
 *
 *      THIS FILE IS AUTOMATICALLY GENERATED.  DO NOT EDIT THIS FILE AS
 *      CHANGES WILL BE OVERWRITTEN.
 *
 *      *************************** WARNING ***************************
 */

#ifndef _ESPCP_ENCODERS_H
#define _ESPCP_ENCODERS_H

#include <stdlib.h>
#include <string.h>
#include "espcp_shared_enums.h"
#include "espcp_message.h"

struct espcp_system_configuration_s
{
    char * software_version;
    uint8_t maximum_message_queue_length;
    uint8_t automatically_start_network;
    uint8_t automatically_reconnect;
    uint32_t maximum_retry_count;
    uint8_t antenna;
    uint8_t mac_address[6];
    char * device_name;
    char * default_access_point;
    char * ntp_server;
    int32_t get_time_at_startup;
    uint8_t use_dhcp;
    uint32_t static_ip_address;
    uint32_t dns_server;
    uint32_t default_gateway;
};
typedef struct espcp_system_configuration_s espcp_system_configuration_t;

struct espcp_wi_fi_credentials_s
{
    char * network_name;
    char * password;
};
typedef struct espcp_wi_fi_credentials_s espcp_wi_fi_credentials_t;

struct espcp_antenna_info_s
{
    uint8_t antenna;
};
typedef struct espcp_antenna_info_s espcp_antenna_info_t;

struct espcp_access_point_s
{
    char ssid[33];
    uint8_t bssid[6];
    uint8_t primary_channel;
    uint8_t secondary_channel;
    int8_t rssi;
    uint8_t authentication_mode;
    uint32_t protocols;
};
typedef struct espcp_access_point_s espcp_access_point_t;

struct espcp_access_point_list_s
{
    uint32_t number_of_access_points;
    uint32_t access_points_length;
    uint8_t *access_points;
};
typedef struct espcp_access_point_list_s espcp_access_point_list_t;

struct espcp_sock_addr_s
{
    uint8_t family;
    uint16_t port;
    uint32_t ip4_address;
    uint32_t flow_info;
    uint8_t ip6_address[16];
    uint32_t scope_i_d;
};
typedef struct espcp_sock_addr_s espcp_sock_addr_t;

struct espcp_addr_info_s
{
    uint32_t my_heap_address;
    int32_t flags;
    int32_t family;
    int32_t socket_type;
    int32_t protocol;
    uint32_t addr_len;
    uint32_t addr_length;
    uint8_t *addr;
    char * canon_name;
    void *next;
};
typedef struct espcp_addr_info_s espcp_addr_info_t;

struct espcp_get_addr_info_request_s
{
    char * node_name;
    char * serv_name;
    uint32_t hints_length;
    uint8_t *hints;
    uint32_t result_length;
    uint8_t *result;
};
typedef struct espcp_get_addr_info_request_s espcp_get_addr_info_request_t;

struct espcp_get_addr_info_response_s
{
    int32_t addr_info_response_errno;
    uint32_t res_length;
    uint8_t *res;
};
typedef struct espcp_get_addr_info_response_s espcp_get_addr_info_response_t;

struct espcp_socket_request_s
{
    void *address_information;
    int32_t domain;
    int32_t type;
    int32_t protocol;
};
typedef struct espcp_socket_request_s espcp_socket_request_t;

struct espcp_integer_response_s
{
    int32_t result;
};
typedef struct espcp_integer_response_s espcp_integer_response_t;

struct espcp_integer_and_errno_response_s
{
    int32_t result;
    int32_t response_errno;
};
typedef struct espcp_integer_and_errno_response_s espcp_integer_and_errno_response_t;

struct espcp_connect_request_s
{
    int32_t socket_handle;
    uint32_t addr_length;
    uint8_t *addr;
};
typedef struct espcp_connect_request_s espcp_connect_request_t;

struct espcp_free_addr_info_request_s
{
    uint32_t addr_info_address;
};
typedef struct espcp_free_addr_info_request_s espcp_free_addr_info_request_t;

struct espcp_time_val_s
{
    uint32_t tv_sec;
    uint32_t tv_usec;
};
typedef struct espcp_time_val_s espcp_time_val_t;

struct espcp_set_sock_opt_request_s
{
    int32_t socket_handle;
    int32_t level;
    int32_t option_name;
    uint32_t option_value_length;
    uint8_t *option_value;
    int32_t option_len;
};
typedef struct espcp_set_sock_opt_request_s espcp_set_sock_opt_request_t;

struct espcp_linger_s
{
    int32_t l_on_off;
    int32_t l_linger;
};
typedef struct espcp_linger_s espcp_linger_t;

struct espcp_write_request_s
{
    int32_t socket_handle;
    uint32_t buffer_length;
    uint8_t *buffer;
    int32_t count;
};
typedef struct espcp_write_request_s espcp_write_request_t;

struct espcp_read_request_s
{
    int32_t socket_handle;
    int32_t count;
};
typedef struct espcp_read_request_s espcp_read_request_t;

struct espcp_read_response_s
{
    uint32_t buffer_length;
    uint8_t *buffer;
    int32_t read_response_result;
    int32_t read_response_errno;
};
typedef struct espcp_read_response_s espcp_read_response_t;

struct espcp_close_request_s
{
    int32_t socket_handle;
};
typedef struct espcp_close_request_s espcp_close_request_t;

struct espcp_get_battery_charge_level_response_s
{
    uint32_t level;
};
typedef struct espcp_get_battery_charge_level_response_s espcp_get_battery_charge_level_response_t;

struct espcp_send_request_s
{
    int32_t socket_handle;
    uint32_t buffer_length;
    uint8_t *buffer;
    int32_t length;
    int32_t flags;
};
typedef struct espcp_send_request_s espcp_send_request_t;

struct espcp_send_to_request_s
{
    int32_t socket_handle;
    uint32_t buffer_length;
    uint8_t *buffer;
    int32_t length;
    int32_t flags;
    uint32_t destination_address_length;
    uint8_t *destination_address;
};
typedef struct espcp_send_to_request_s espcp_send_to_request_t;

struct espcp_recv_from_request_s
{
    int32_t socket_handle;
    int32_t length;
    int32_t flags;
    int32_t get_source_address;
};
typedef struct espcp_recv_from_request_s espcp_recv_from_request_t;

struct espcp_recv_from_response_s
{
    uint32_t buffer_length;
    uint8_t *buffer;
    int32_t result;
    int32_t response_errno;
    uint32_t source_address_length;
    uint8_t *source_address;
    uint32_t source_address_len;
};
typedef struct espcp_recv_from_response_s espcp_recv_from_response_t;

struct espcp_poll_request_s
{
    int32_t socket_handle;
    uint16_t events;
    int32_t timeout;
    int32_t setup;
    uint32_t setup_message_id;
};
typedef struct espcp_poll_request_s espcp_poll_request_t;

struct espcp_poll_response_s
{
    uint16_t returned_events;
    int32_t result;
    int32_t response_errno;
};
typedef struct espcp_poll_response_s espcp_poll_response_t;

struct espcp_interrupt_poll_response_s
{
    int32_t socket_handle;
    int32_t result;
    int32_t response_errno;
    uint16_t returned_events;
    uint32_t setup_message_id;
};
typedef struct espcp_interrupt_poll_response_s espcp_interrupt_poll_response_t;


/*
 *      Encoding methods for the ESP32 SPI communications layer.
 *
 *      Functionality includes:
 *          - Encoding 16 / 32 bit values into buffers.
 *          - extract_ing 16 / 32 bit values from buffer.
 *          - CRC calculations.
 */

/*
 *      Seed for the 32-bit CRC calculation.
 */
#define ESPCP_CRC32_SEED 0xffffffff

/*
 *      Offset of the CRC into the message header.
 */
#define ESPCP_CRC_OFFSET 18

/*
 *      Number of bytes actually used in a message header.
 */
#define ESPCP_HEADER_SIZE 23

uint32_t espcp_calculate_spi_buffer_size(uint32_t);
uint16_t espcp_extract_uint16(uint8_t *);
void espcp_encode_uint16(uint16_t, uint8_t *);
uint32_t espcp_extract_uint32(uint8_t *);
void espcp_encode_uint32(uint32_t, uint8_t *);
int32_t espcp_extract_int32(uint8_t *);
void espcp_encode_int32(int32_t, uint8_t *);
char *espcp_extract_string(uint8_t *);
void espcp_encode_string(char *, uint8_t *);
uint32_t espcp_string_length(char *);
uint8_t espcp_crc8(const uint8_t *, uint16_t);
uint32_t espcp_crc32(const uint8_t *, uint16_t);
uint32_t espcp_progressive_crc32(uint32_t, uint8_t);
espcp_message_t *espcp_extract_message(uint8_t *, uint32_t, bool);
uint8_t *espcp_encode_message(espcp_message_t *, uint32_t *, bool);void espcp_encode_system_configuration(espcp_system_configuration_t *, uint8_t *);
int espcp_system_configuration_buffer_size(espcp_system_configuration_t *);
espcp_system_configuration_t *espcp_extract_system_configuration(uint8_t *);
void espcp_encode_wi_fi_credentials(espcp_wi_fi_credentials_t *, uint8_t *);
int espcp_wi_fi_credentials_buffer_size(espcp_wi_fi_credentials_t *);
espcp_wi_fi_credentials_t *espcp_extract_wi_fi_credentials(uint8_t *);
void espcp_encode_antenna_info(espcp_antenna_info_t *, uint8_t *);
int espcp_antenna_info_buffer_size(espcp_antenna_info_t *);
espcp_antenna_info_t *espcp_extract_antenna_info(uint8_t *);
void espcp_encode_access_point(espcp_access_point_t *, uint8_t *);
int espcp_access_point_buffer_size(espcp_access_point_t *);
espcp_access_point_t *espcp_extract_access_point(uint8_t *);
void espcp_encode_access_point_list(espcp_access_point_list_t *, uint8_t *);
int espcp_access_point_list_buffer_size(espcp_access_point_list_t *);
espcp_access_point_list_t *espcp_extract_access_point_list(uint8_t *);
void espcp_encode_sock_addr(espcp_sock_addr_t *, uint8_t *);
int espcp_sock_addr_buffer_size(espcp_sock_addr_t *);
espcp_sock_addr_t *espcp_extract_sock_addr(uint8_t *);
void espcp_encode_addr_info(espcp_addr_info_t *, uint8_t *);
int espcp_addr_info_buffer_size(espcp_addr_info_t *);
espcp_addr_info_t *espcp_extract_addr_info(uint8_t *);
void espcp_encode_get_addr_info_request(espcp_get_addr_info_request_t *, uint8_t *);
int espcp_get_addr_info_request_buffer_size(espcp_get_addr_info_request_t *);
espcp_get_addr_info_request_t *espcp_extract_get_addr_info_request(uint8_t *);
void espcp_encode_get_addr_info_response(espcp_get_addr_info_response_t *, uint8_t *);
int espcp_get_addr_info_response_buffer_size(espcp_get_addr_info_response_t *);
espcp_get_addr_info_response_t *espcp_extract_get_addr_info_response(uint8_t *);
void espcp_encode_socket_request(espcp_socket_request_t *, uint8_t *);
int espcp_socket_request_buffer_size(espcp_socket_request_t *);
espcp_socket_request_t *espcp_extract_socket_request(uint8_t *);
void espcp_encode_integer_response(espcp_integer_response_t *, uint8_t *);
int espcp_integer_response_buffer_size(espcp_integer_response_t *);
espcp_integer_response_t *espcp_extract_integer_response(uint8_t *);
void espcp_encode_integer_and_errno_response(espcp_integer_and_errno_response_t *, uint8_t *);
int espcp_integer_and_errno_response_buffer_size(espcp_integer_and_errno_response_t *);
espcp_integer_and_errno_response_t *espcp_extract_integer_and_errno_response(uint8_t *);
void espcp_encode_connect_request(espcp_connect_request_t *, uint8_t *);
int espcp_connect_request_buffer_size(espcp_connect_request_t *);
espcp_connect_request_t *espcp_extract_connect_request(uint8_t *);
void espcp_encode_free_addr_info_request(espcp_free_addr_info_request_t *, uint8_t *);
int espcp_free_addr_info_request_buffer_size(espcp_free_addr_info_request_t *);
espcp_free_addr_info_request_t *espcp_extract_free_addr_info_request(uint8_t *);
void espcp_encode_time_val(espcp_time_val_t *, uint8_t *);
int espcp_time_val_buffer_size(espcp_time_val_t *);
espcp_time_val_t *espcp_extract_time_val(uint8_t *);
void espcp_encode_set_sock_opt_request(espcp_set_sock_opt_request_t *, uint8_t *);
int espcp_set_sock_opt_request_buffer_size(espcp_set_sock_opt_request_t *);
espcp_set_sock_opt_request_t *espcp_extract_set_sock_opt_request(uint8_t *);
void espcp_encode_linger(espcp_linger_t *, uint8_t *);
int espcp_linger_buffer_size(espcp_linger_t *);
espcp_linger_t *espcp_extract_linger(uint8_t *);
void espcp_encode_write_request(espcp_write_request_t *, uint8_t *);
int espcp_write_request_buffer_size(espcp_write_request_t *);
espcp_write_request_t *espcp_extract_write_request(uint8_t *);
void espcp_encode_read_request(espcp_read_request_t *, uint8_t *);
int espcp_read_request_buffer_size(espcp_read_request_t *);
espcp_read_request_t *espcp_extract_read_request(uint8_t *);
void espcp_encode_read_response(espcp_read_response_t *, uint8_t *);
int espcp_read_response_buffer_size(espcp_read_response_t *);
espcp_read_response_t *espcp_extract_read_response(uint8_t *);
void espcp_encode_close_request(espcp_close_request_t *, uint8_t *);
int espcp_close_request_buffer_size(espcp_close_request_t *);
espcp_close_request_t *espcp_extract_close_request(uint8_t *);
void espcp_encode_get_battery_charge_level_response(espcp_get_battery_charge_level_response_t *, uint8_t *);
int espcp_get_battery_charge_level_response_buffer_size(espcp_get_battery_charge_level_response_t *);
espcp_get_battery_charge_level_response_t *espcp_extract_get_battery_charge_level_response(uint8_t *);
void espcp_encode_send_request(espcp_send_request_t *, uint8_t *);
int espcp_send_request_buffer_size(espcp_send_request_t *);
espcp_send_request_t *espcp_extract_send_request(uint8_t *);
void espcp_encode_send_to_request(espcp_send_to_request_t *, uint8_t *);
int espcp_send_to_request_buffer_size(espcp_send_to_request_t *);
espcp_send_to_request_t *espcp_extract_send_to_request(uint8_t *);
void espcp_encode_recv_from_request(espcp_recv_from_request_t *, uint8_t *);
int espcp_recv_from_request_buffer_size(espcp_recv_from_request_t *);
espcp_recv_from_request_t *espcp_extract_recv_from_request(uint8_t *);
void espcp_encode_recv_from_response(espcp_recv_from_response_t *, uint8_t *);
int espcp_recv_from_response_buffer_size(espcp_recv_from_response_t *);
espcp_recv_from_response_t *espcp_extract_recv_from_response(uint8_t *);
void espcp_encode_poll_request(espcp_poll_request_t *, uint8_t *);
int espcp_poll_request_buffer_size(espcp_poll_request_t *);
espcp_poll_request_t *espcp_extract_poll_request(uint8_t *);
void espcp_encode_poll_response(espcp_poll_response_t *, uint8_t *);
int espcp_poll_response_buffer_size(espcp_poll_response_t *);
espcp_poll_response_t *espcp_extract_poll_response(uint8_t *);
void espcp_encode_interrupt_poll_response(espcp_interrupt_poll_response_t *, uint8_t *);
int espcp_interrupt_poll_response_buffer_size(espcp_interrupt_poll_response_t *);
espcp_interrupt_poll_response_t *espcp_extract_interrupt_poll_response(uint8_t *);


#endif /* _ESPCP_ENCODERS_H */

