/*
 *      Encoders.hpp
 *
 *      Message encoders and decoders.
 *
 *      *************************** WARNING ***************************
 *
 *      THIS FILE IS AUTOMATICALLY GENERATED.  DO NOT EDIT THIS FILE AS
 *      CHANGES WILL BE OVERWRITTEN.
 *
 *      *************************** WARNING ***************************
 */

#ifndef _ENCODERS_HPP
#define _ENCODERS_HPP

#include "freertos/FreeRTOS.h"
#include "lwip/err.h"
#include "lwip/sys.h"
#include "lwip/sockets.h"
#include "lwip/netdb.h"
#include "lwip/dns.h"
#include "esp_system.h"
#include "esp_wifi.h"
#include <stdlib.h>
#include <string.h>
#include "esp_log.h"
#include "SharedEnums.hpp"
#include "Esp32Messaging.hpp"

namespace Esp32Messaging
{
    struct SystemConfiguration
    {
        uint8_t MaximumMessageQueueLength;
        int32_t MaximumRetryCount;
        uint8_t Antenna;
        uint8_t BoardMacAddress[6];
        uint8_t SoftApMacAddress[6];
        uint8_t BluetoothMacAddress[6];
        char * DeviceName;
        char * DefaultAccessPoint;
        uint8_t ResetReason;
        uint32_t VersionMajor;
        uint32_t VersionMinor;
        uint32_t VersionRevision;
        uint32_t VersionBuild;
        uint8_t BuildDay;
        uint8_t BuildMonth;
        uint8_t BuildYear;
        uint8_t BuildHour;
        uint8_t BuildMinute;
        uint8_t BuildSecond;
        uint32_t BuildHash;
        char * BuildBranchName;
    };

    struct ConfigurationValue
    {
        uint32_t Item;
        uint32_t ValueLength;
        uint8_t *Value;
    };

    struct ErrorEvent
    {
        uint32_t ErrorCode;
        uint8_t Interface;
        uint32_t ErrorDataLength;
        uint8_t *ErrorData;
    };

    struct AccessPointInformation
    {
        char * NetworkName;
        char * Password;
        uint32_t IpAddress;
        uint32_t SubnetMask;
        uint32_t Gateway;
        uint8_t WiFiAuthenticationMode;
        uint8_t Channel;
        uint8_t Hidden;
    };

    struct DisconnectFromAccessPointRequest
    {
        uint8_t TurnOffWiFiInterface;
    };

    struct ConnectEventData
    {
        uint32_t IpAddress;
        uint32_t SubnetMask;
        uint32_t Gateway;
        char Ssid[33];
        uint8_t Bssid[6];
        uint8_t Channel;
        uint8_t AuthenticationMode;
        uint32_t Reason;
    };

    struct NodeConnectionChangeEventData
    {
        uint32_t IpAddress;
        uint8_t MacAddress[6];
    };

    struct DisconnectEventData
    {
        uint8_t Retrying;
        int32_t RetriesRemaining;
        uint32_t Reason;
    };

    struct AccessPoint
    {
        char Ssid[33];
        uint8_t Bssid[6];
        uint8_t PrimaryChannel;
        uint8_t SecondaryChannel;
        int8_t Rssi;
        uint8_t AuthenticationMode;
        uint32_t Protocols;
    };

    struct AccessPointList
    {
        uint32_t NumberOfAccessPoints;
        uint32_t AccessPointsLength;
        uint8_t *AccessPoints;
    };

    struct SockAddr
    {
        uint8_t Family;
        uint16_t Port;
        uint32_t Ip4Address;
        uint32_t FlowInfo;
        uint8_t Ip6Address[16];
        uint32_t ScopeID;
    };

    struct AddrInfo
    {
        uint32_t MyHeapAddress;
        int32_t Flags;
        int32_t Family;
        int32_t SocketType;
        int32_t Protocol;
        uint32_t AddrLen;
        uint32_t AddrLength;
        uint8_t *Addr;
        char * CanonName;
        void *Next;
    };

    struct GetAddrInfoRequest
    {
        char * NodeName;
        char * ServName;
        uint32_t HintsLength;
        uint8_t *Hints;
    };

    struct GetAddrInfoResponse
    {
        int32_t AddrInfoResponseErrno;
        uint32_t ResLength;
        uint8_t *Res;
    };

    struct SocketRequest
    {
        void *AddressInformation;
        int32_t Domain;
        int32_t Type;
        int32_t Protocol;
    };

    struct IntegerResponse
    {
        int32_t Result;
    };

    struct IntegerAndErrnoResponse
    {
        int32_t Result;
        int32_t ResponseErrno;
    };

    struct ConnectRequest
    {
        int32_t SocketHandle;
        uint32_t AddrLength;
        uint8_t *Addr;
    };

    struct FreeAddrInfoRequest
    {
        uint32_t AddrInfoAddress;
    };

    struct TimeVal
    {
        uint32_t TvSec;
        uint32_t TvUsec;
    };

    struct SetSockOptRequest
    {
        int32_t SocketHandle;
        int32_t Level;
        int32_t OptionName;
        uint32_t OptionValueLength;
        uint8_t *OptionValue;
        int32_t OptionLen;
    };

    struct GetSockOptRequest
    {
        int32_t SocketHandle;
        int32_t Level;
        int32_t OptionName;
    };

    struct GetSockOptResponse
    {
        int32_t Result;
        int32_t ResponseErrno;
        uint32_t OptionValueLength;
        uint8_t *OptionValue;
        int32_t OptionLen;
    };

    struct Linger
    {
        int32_t LOnOff;
        int32_t LLinger;
    };

    struct WriteRequest
    {
        int32_t SocketHandle;
        uint32_t BufferLength;
        uint8_t *Buffer;
        int32_t Count;
    };

    struct ReadRequest
    {
        int32_t SocketHandle;
        int32_t Count;
    };

    struct ReadResponse
    {
        uint32_t BufferLength;
        uint8_t *Buffer;
        int32_t ReadResponseResult;
        int32_t ReadResponseErrno;
    };

    struct CloseRequest
    {
        int32_t SocketHandle;
    };

    struct GetBatteryChargeLevelResponse
    {
        uint32_t Level;
    };

    struct SendRequest
    {
        int32_t SocketHandle;
        uint32_t BufferLength;
        uint8_t *Buffer;
        int32_t Length;
        int32_t Flags;
    };

    struct SendToRequest
    {
        int32_t SocketHandle;
        uint32_t BufferLength;
        uint8_t *Buffer;
        int32_t Length;
        int32_t Flags;
        uint32_t DestinationAddressLength;
        uint8_t *DestinationAddress;
    };

    struct RecvFromRequest
    {
        int32_t SocketHandle;
        int32_t Length;
        int32_t Flags;
        int32_t GetSourceAddress;
    };

    struct RecvFromResponse
    {
        uint32_t BufferLength;
        uint8_t *Buffer;
        int32_t Result;
        int32_t ResponseErrno;
        uint32_t SourceAddressLength;
        uint8_t *SourceAddress;
        uint32_t SourceAddressLen;
    };

    struct PollRequest
    {
        int32_t SocketHandle;
        uint16_t Events;
        int32_t Timeout;
        int32_t Setup;
        uint32_t SetupMessageId;
    };

    struct PollResponse
    {
        uint16_t ReturnedEvents;
        int32_t Result;
        int32_t ResponseErrno;
    };

    struct InterruptPollResponse
    {
        int32_t SocketHandle;
        int32_t Result;
        int32_t ResponseErrno;
        uint16_t ReturnedEvents;
        uint32_t SetupMessageId;
    };

    struct ListenRequest
    {
        int32_t SocketHandle;
        int32_t BackLog;
    };

    struct BindRequest
    {
        int32_t SocketHandle;
        uint32_t AddrLength;
        uint8_t *Addr;
    };

    struct AcceptRequest
    {
        int32_t SocketHandle;
    };

    struct AcceptResponse
    {
        uint32_t AddrLength;
        uint8_t *Addr;
        int32_t Result;
        int32_t ResponseErrno;
    };

    struct IoctlRequest
    {
        int32_t Command;
    };

    struct IoctlResponse
    {
        uint32_t AddrLength;
        uint8_t *Addr;
        int32_t Flags;
        int32_t Result;
        int32_t ResponseErrno;
    };

    struct GetSockPeerNameRequest
    {
        int32_t SocketHandle;
    };

    struct GetSockPeerNameResponse
    {
        uint32_t AddrLength;
        uint8_t *Addr;
        int32_t Result;
        int32_t ResponseErrno;
    };

    struct EventData
    {
        uint8_t Interface;
        uint32_t Function;
        uint32_t StatusCode;
        uint32_t MessageId;
    };

    struct EventDataPayload
    {
        uint32_t MessageId;
        uint32_t PayloadLength;
        uint8_t *Payload;
    };

    struct SetAntennaRequest
    {
        uint8_t Antenna;
        uint8_t Persist;
    };

    struct BTStackConfig
    {
        char * Config;
    };

    struct BTDataWriteRequest
    {
        uint16_t Handle;
        uint32_t DataLength;
        uint8_t *Data;
    };

    struct BTGetHandlesResponse
    {
        uint16_t HandleCount;
        uint32_t HandlesLength;
        uint8_t *Handles;
    };

    struct BTServerDataSet
    {
        uint16_t Handle;
        uint32_t SetDataLength;
        uint8_t *SetData;
    };

    struct FileDetails
    {
        char * Name;
        uint16_t Length;
    };

    struct FileNameAndContents
    {
        char * Name;
        uint32_t ContentsLength;
        uint8_t *Contents;
    };

    struct FileNameList
    {
        uint16_t NumberOfFiles;
        uint32_t FileDetailsLength;
        uint8_t *FileDetails;
    };

}

/*
 *      Class holding the encoding methods.
 *
 *      Functionality includes:
 *          - Encoding 16 / 32 bit values into buffers.
 *          - Extracting 16 / 32 bit values from buffer.
 *          - CRC calculations.
 */
class Encoders
{
public:
    /*
     *      Seed for the 32-bit CRC calculation.
     */
    static const uint32_t CRC32_SEED = 0xffffffff;
    static uint32_t CalculateSpiBufferSize(uint32_t);
    static uint32_t EncodedPacketSize(Message *, bool);
    static uint16_t ExtractUInt16(uint8_t *);
    static void EncodeUInt16(uint16_t, uint8_t *);
    static uint32_t ExtractUInt32(uint8_t *);
    static void EncodeUInt32(uint32_t, uint8_t *);
    static uint32_t ExtractInt32(uint8_t *);
    static void EncodeInt32(int32_t, uint8_t *);
    static char *ExtractString(uint8_t *);
    static void EncodeString(char *, uint8_t *);
    static uint32_t StringLength(char *);
    static uint8_t CRC8(const uint8_t *, uint16_t);
    static uint32_t CRC32(const uint8_t *, uint16_t);
    static uint32_t ProgressiveCRC32(uint32_t, uint8_t);
    static void EncodeMessage(Message *, uint8_t*, bool);
    static Message *ExtractMessage(uint8_t *, uint32_t, bool);
    static void EncodeSystemConfiguration(Esp32Messaging::SystemConfiguration *, uint8_t *);
    static int EncodedSystemConfigurationBufferSize(Esp32Messaging::SystemConfiguration *);
    static Esp32Messaging::SystemConfiguration *ExtractSystemConfiguration(uint8_t *);
    static void EncodeConfigurationValue(Esp32Messaging::ConfigurationValue *, uint8_t *);
    static int EncodedConfigurationValueBufferSize(Esp32Messaging::ConfigurationValue *);
    static Esp32Messaging::ConfigurationValue *ExtractConfigurationValue(uint8_t *);
    static void EncodeErrorEvent(Esp32Messaging::ErrorEvent *, uint8_t *);
    static int EncodedErrorEventBufferSize(Esp32Messaging::ErrorEvent *);
    static Esp32Messaging::ErrorEvent *ExtractErrorEvent(uint8_t *);
    static void EncodeAccessPointInformation(Esp32Messaging::AccessPointInformation *, uint8_t *);
    static int EncodedAccessPointInformationBufferSize(Esp32Messaging::AccessPointInformation *);
    static Esp32Messaging::AccessPointInformation *ExtractAccessPointInformation(uint8_t *);
    static void EncodeDisconnectFromAccessPointRequest(Esp32Messaging::DisconnectFromAccessPointRequest *, uint8_t *);
    static int EncodedDisconnectFromAccessPointRequestBufferSize(Esp32Messaging::DisconnectFromAccessPointRequest *);
    static Esp32Messaging::DisconnectFromAccessPointRequest *ExtractDisconnectFromAccessPointRequest(uint8_t *);
    static void EncodeConnectEventData(Esp32Messaging::ConnectEventData *, uint8_t *);
    static int EncodedConnectEventDataBufferSize(Esp32Messaging::ConnectEventData *);
    static Esp32Messaging::ConnectEventData *ExtractConnectEventData(uint8_t *);
    static void EncodeNodeConnectionChangeEventData(Esp32Messaging::NodeConnectionChangeEventData *, uint8_t *);
    static int EncodedNodeConnectionChangeEventDataBufferSize(Esp32Messaging::NodeConnectionChangeEventData *);
    static Esp32Messaging::NodeConnectionChangeEventData *ExtractNodeConnectionChangeEventData(uint8_t *);
    static void EncodeDisconnectEventData(Esp32Messaging::DisconnectEventData *, uint8_t *);
    static int EncodedDisconnectEventDataBufferSize(Esp32Messaging::DisconnectEventData *);
    static Esp32Messaging::DisconnectEventData *ExtractDisconnectEventData(uint8_t *);
    static void EncodeAccessPoint(Esp32Messaging::AccessPoint *, uint8_t *);
    static int EncodedAccessPointBufferSize(Esp32Messaging::AccessPoint *);
    static Esp32Messaging::AccessPoint *ExtractAccessPoint(uint8_t *);
    static void EncodeAccessPointList(Esp32Messaging::AccessPointList *, uint8_t *);
    static int EncodedAccessPointListBufferSize(Esp32Messaging::AccessPointList *);
    static Esp32Messaging::AccessPointList *ExtractAccessPointList(uint8_t *);
    static void EncodeSockAddr(Esp32Messaging::SockAddr *, uint8_t *);
    static int EncodedSockAddrBufferSize(Esp32Messaging::SockAddr *);
    static Esp32Messaging::SockAddr *ExtractSockAddr(uint8_t *);
    static void EncodeAddrInfo(Esp32Messaging::AddrInfo *, uint8_t *);
    static int EncodedAddrInfoBufferSize(Esp32Messaging::AddrInfo *);
    static Esp32Messaging::AddrInfo *ExtractAddrInfo(uint8_t *);
    static void EncodeGetAddrInfoRequest(Esp32Messaging::GetAddrInfoRequest *, uint8_t *);
    static int EncodedGetAddrInfoRequestBufferSize(Esp32Messaging::GetAddrInfoRequest *);
    static Esp32Messaging::GetAddrInfoRequest *ExtractGetAddrInfoRequest(uint8_t *);
    static void EncodeGetAddrInfoResponse(Esp32Messaging::GetAddrInfoResponse *, uint8_t *);
    static int EncodedGetAddrInfoResponseBufferSize(Esp32Messaging::GetAddrInfoResponse *);
    static Esp32Messaging::GetAddrInfoResponse *ExtractGetAddrInfoResponse(uint8_t *);
    static void EncodeSocketRequest(Esp32Messaging::SocketRequest *, uint8_t *);
    static int EncodedSocketRequestBufferSize(Esp32Messaging::SocketRequest *);
    static Esp32Messaging::SocketRequest *ExtractSocketRequest(uint8_t *);
    static void EncodeIntegerResponse(Esp32Messaging::IntegerResponse *, uint8_t *);
    static int EncodedIntegerResponseBufferSize(Esp32Messaging::IntegerResponse *);
    static Esp32Messaging::IntegerResponse *ExtractIntegerResponse(uint8_t *);
    static void EncodeIntegerAndErrnoResponse(Esp32Messaging::IntegerAndErrnoResponse *, uint8_t *);
    static int EncodedIntegerAndErrnoResponseBufferSize(Esp32Messaging::IntegerAndErrnoResponse *);
    static Esp32Messaging::IntegerAndErrnoResponse *ExtractIntegerAndErrnoResponse(uint8_t *);
    static void EncodeConnectRequest(Esp32Messaging::ConnectRequest *, uint8_t *);
    static int EncodedConnectRequestBufferSize(Esp32Messaging::ConnectRequest *);
    static Esp32Messaging::ConnectRequest *ExtractConnectRequest(uint8_t *);
    static void EncodeFreeAddrInfoRequest(Esp32Messaging::FreeAddrInfoRequest *, uint8_t *);
    static int EncodedFreeAddrInfoRequestBufferSize(Esp32Messaging::FreeAddrInfoRequest *);
    static Esp32Messaging::FreeAddrInfoRequest *ExtractFreeAddrInfoRequest(uint8_t *);
    static void EncodeTimeVal(Esp32Messaging::TimeVal *, uint8_t *);
    static int EncodedTimeValBufferSize(Esp32Messaging::TimeVal *);
    static Esp32Messaging::TimeVal *ExtractTimeVal(uint8_t *);
    static void EncodeSetSockOptRequest(Esp32Messaging::SetSockOptRequest *, uint8_t *);
    static int EncodedSetSockOptRequestBufferSize(Esp32Messaging::SetSockOptRequest *);
    static Esp32Messaging::SetSockOptRequest *ExtractSetSockOptRequest(uint8_t *);
    static void EncodeGetSockOptRequest(Esp32Messaging::GetSockOptRequest *, uint8_t *);
    static int EncodedGetSockOptRequestBufferSize(Esp32Messaging::GetSockOptRequest *);
    static Esp32Messaging::GetSockOptRequest *ExtractGetSockOptRequest(uint8_t *);
    static void EncodeGetSockOptResponse(Esp32Messaging::GetSockOptResponse *, uint8_t *);
    static int EncodedGetSockOptResponseBufferSize(Esp32Messaging::GetSockOptResponse *);
    static Esp32Messaging::GetSockOptResponse *ExtractGetSockOptResponse(uint8_t *);
    static void EncodeLinger(Esp32Messaging::Linger *, uint8_t *);
    static int EncodedLingerBufferSize(Esp32Messaging::Linger *);
    static Esp32Messaging::Linger *ExtractLinger(uint8_t *);
    static void EncodeWriteRequest(Esp32Messaging::WriteRequest *, uint8_t *);
    static int EncodedWriteRequestBufferSize(Esp32Messaging::WriteRequest *);
    static Esp32Messaging::WriteRequest *ExtractWriteRequest(uint8_t *);
    static void EncodeReadRequest(Esp32Messaging::ReadRequest *, uint8_t *);
    static int EncodedReadRequestBufferSize(Esp32Messaging::ReadRequest *);
    static Esp32Messaging::ReadRequest *ExtractReadRequest(uint8_t *);
    static void EncodeReadResponse(Esp32Messaging::ReadResponse *, uint8_t *);
    static int EncodedReadResponseBufferSize(Esp32Messaging::ReadResponse *);
    static Esp32Messaging::ReadResponse *ExtractReadResponse(uint8_t *);
    static void EncodeCloseRequest(Esp32Messaging::CloseRequest *, uint8_t *);
    static int EncodedCloseRequestBufferSize(Esp32Messaging::CloseRequest *);
    static Esp32Messaging::CloseRequest *ExtractCloseRequest(uint8_t *);
    static void EncodeGetBatteryChargeLevelResponse(Esp32Messaging::GetBatteryChargeLevelResponse *, uint8_t *);
    static int EncodedGetBatteryChargeLevelResponseBufferSize(Esp32Messaging::GetBatteryChargeLevelResponse *);
    static Esp32Messaging::GetBatteryChargeLevelResponse *ExtractGetBatteryChargeLevelResponse(uint8_t *);
    static void EncodeSendRequest(Esp32Messaging::SendRequest *, uint8_t *);
    static int EncodedSendRequestBufferSize(Esp32Messaging::SendRequest *);
    static Esp32Messaging::SendRequest *ExtractSendRequest(uint8_t *);
    static void EncodeSendToRequest(Esp32Messaging::SendToRequest *, uint8_t *);
    static int EncodedSendToRequestBufferSize(Esp32Messaging::SendToRequest *);
    static Esp32Messaging::SendToRequest *ExtractSendToRequest(uint8_t *);
    static void EncodeRecvFromRequest(Esp32Messaging::RecvFromRequest *, uint8_t *);
    static int EncodedRecvFromRequestBufferSize(Esp32Messaging::RecvFromRequest *);
    static Esp32Messaging::RecvFromRequest *ExtractRecvFromRequest(uint8_t *);
    static void EncodeRecvFromResponse(Esp32Messaging::RecvFromResponse *, uint8_t *);
    static int EncodedRecvFromResponseBufferSize(Esp32Messaging::RecvFromResponse *);
    static Esp32Messaging::RecvFromResponse *ExtractRecvFromResponse(uint8_t *);
    static void EncodePollRequest(Esp32Messaging::PollRequest *, uint8_t *);
    static int EncodedPollRequestBufferSize(Esp32Messaging::PollRequest *);
    static Esp32Messaging::PollRequest *ExtractPollRequest(uint8_t *);
    static void EncodePollResponse(Esp32Messaging::PollResponse *, uint8_t *);
    static int EncodedPollResponseBufferSize(Esp32Messaging::PollResponse *);
    static Esp32Messaging::PollResponse *ExtractPollResponse(uint8_t *);
    static void EncodeInterruptPollResponse(Esp32Messaging::InterruptPollResponse *, uint8_t *);
    static int EncodedInterruptPollResponseBufferSize(Esp32Messaging::InterruptPollResponse *);
    static Esp32Messaging::InterruptPollResponse *ExtractInterruptPollResponse(uint8_t *);
    static void EncodeListenRequest(Esp32Messaging::ListenRequest *, uint8_t *);
    static int EncodedListenRequestBufferSize(Esp32Messaging::ListenRequest *);
    static Esp32Messaging::ListenRequest *ExtractListenRequest(uint8_t *);
    static void EncodeBindRequest(Esp32Messaging::BindRequest *, uint8_t *);
    static int EncodedBindRequestBufferSize(Esp32Messaging::BindRequest *);
    static Esp32Messaging::BindRequest *ExtractBindRequest(uint8_t *);
    static void EncodeAcceptRequest(Esp32Messaging::AcceptRequest *, uint8_t *);
    static int EncodedAcceptRequestBufferSize(Esp32Messaging::AcceptRequest *);
    static Esp32Messaging::AcceptRequest *ExtractAcceptRequest(uint8_t *);
    static void EncodeAcceptResponse(Esp32Messaging::AcceptResponse *, uint8_t *);
    static int EncodedAcceptResponseBufferSize(Esp32Messaging::AcceptResponse *);
    static Esp32Messaging::AcceptResponse *ExtractAcceptResponse(uint8_t *);
    static void EncodeIoctlRequest(Esp32Messaging::IoctlRequest *, uint8_t *);
    static int EncodedIoctlRequestBufferSize(Esp32Messaging::IoctlRequest *);
    static Esp32Messaging::IoctlRequest *ExtractIoctlRequest(uint8_t *);
    static void EncodeIoctlResponse(Esp32Messaging::IoctlResponse *, uint8_t *);
    static int EncodedIoctlResponseBufferSize(Esp32Messaging::IoctlResponse *);
    static Esp32Messaging::IoctlResponse *ExtractIoctlResponse(uint8_t *);
    static void EncodeGetSockPeerNameRequest(Esp32Messaging::GetSockPeerNameRequest *, uint8_t *);
    static int EncodedGetSockPeerNameRequestBufferSize(Esp32Messaging::GetSockPeerNameRequest *);
    static Esp32Messaging::GetSockPeerNameRequest *ExtractGetSockPeerNameRequest(uint8_t *);
    static void EncodeGetSockPeerNameResponse(Esp32Messaging::GetSockPeerNameResponse *, uint8_t *);
    static int EncodedGetSockPeerNameResponseBufferSize(Esp32Messaging::GetSockPeerNameResponse *);
    static Esp32Messaging::GetSockPeerNameResponse *ExtractGetSockPeerNameResponse(uint8_t *);
    static void EncodeEventData(Esp32Messaging::EventData *, uint8_t *);
    static int EncodedEventDataBufferSize(Esp32Messaging::EventData *);
    static Esp32Messaging::EventData *ExtractEventData(uint8_t *);
    static void EncodeEventDataPayload(Esp32Messaging::EventDataPayload *, uint8_t *);
    static int EncodedEventDataPayloadBufferSize(Esp32Messaging::EventDataPayload *);
    static Esp32Messaging::EventDataPayload *ExtractEventDataPayload(uint8_t *);
    static void EncodeSetAntennaRequest(Esp32Messaging::SetAntennaRequest *, uint8_t *);
    static int EncodedSetAntennaRequestBufferSize(Esp32Messaging::SetAntennaRequest *);
    static Esp32Messaging::SetAntennaRequest *ExtractSetAntennaRequest(uint8_t *);
    static void EncodeBTStackConfig(Esp32Messaging::BTStackConfig *, uint8_t *);
    static int EncodedBTStackConfigBufferSize(Esp32Messaging::BTStackConfig *);
    static Esp32Messaging::BTStackConfig *ExtractBTStackConfig(uint8_t *);
    static void EncodeBTDataWriteRequest(Esp32Messaging::BTDataWriteRequest *, uint8_t *);
    static int EncodedBTDataWriteRequestBufferSize(Esp32Messaging::BTDataWriteRequest *);
    static Esp32Messaging::BTDataWriteRequest *ExtractBTDataWriteRequest(uint8_t *);
    static void EncodeBTGetHandlesResponse(Esp32Messaging::BTGetHandlesResponse *, uint8_t *);
    static int EncodedBTGetHandlesResponseBufferSize(Esp32Messaging::BTGetHandlesResponse *);
    static Esp32Messaging::BTGetHandlesResponse *ExtractBTGetHandlesResponse(uint8_t *);
    static void EncodeBTServerDataSet(Esp32Messaging::BTServerDataSet *, uint8_t *);
    static int EncodedBTServerDataSetBufferSize(Esp32Messaging::BTServerDataSet *);
    static Esp32Messaging::BTServerDataSet *ExtractBTServerDataSet(uint8_t *);
    static void EncodeFileDetails(Esp32Messaging::FileDetails *, uint8_t *);
    static int EncodedFileDetailsBufferSize(Esp32Messaging::FileDetails *);
    static Esp32Messaging::FileDetails *ExtractFileDetails(uint8_t *);
    static void EncodeFileNameAndContents(Esp32Messaging::FileNameAndContents *, uint8_t *);
    static int EncodedFileNameAndContentsBufferSize(Esp32Messaging::FileNameAndContents *);
    static Esp32Messaging::FileNameAndContents *ExtractFileNameAndContents(uint8_t *);
    static void EncodeFileNameList(Esp32Messaging::FileNameList *, uint8_t *);
    static int EncodedFileNameListBufferSize(Esp32Messaging::FileNameList *);
    static Esp32Messaging::FileNameList *ExtractFileNameList(uint8_t *);

};

#endif /* _ENCODERS_HPP */

