/*
 *  RequestHandlerBase.cpp
 *
 *  Base class for the request handlers.
 */
#include "sdkconfig.h"

#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/queue.h"
#include "esp_log.h"

#include "Encoders.hpp"
#include "RequestHandlerBase.hpp"
#include "Logging.hpp"
#include "MessageDispatcher.hpp"

/*
 * ---------------------------------------------------------------------------
 *
 *                     Initialise static data.
 *
 * ---------------------------------------------------------------------------
 */

/**
 *  @brief Name of this component / task.
 */
const char *RequestHandlerBase::COMPONENT_NAME = "RequestHandlerBase";

/**
 *  @brief MessageDispatcher object that ensure that messages are delivered to
 *  the correct part of the system.
 */
IMessageDispatcher *RequestHandlerBase::_messageDispatcher = nullptr;

/*
 * ---------------------------------------------------------------------------
 *
 *                     Constructors and destructor
 *
 * ---------------------------------------------------------------------------
 */

/**
 *  @brief Constructor for the RequestHandlerBase class.
 */
RequestHandlerBase::RequestHandlerBase() : _queueHandle(nullptr), _taskHandle(nullptr)
{
}

/**
 *  @brief Create a new request handler object and ensure that
 *  the message dispatcher reference is set up correctly.
 *
 *  @param messageDispatcher
 *      Message dispatcher object that will allow communication
 *      with the STM32.
 */
RequestHandlerBase::RequestHandlerBase(IMessageDispatcher *messageDispatcher) : RequestHandlerBase()
{
    _messageDispatcher = messageDispatcher;
}

/**
 *  @brief Destructor for the RequestHandlerBase class.
 */
RequestHandlerBase::~RequestHandlerBase()
{
}

/*
 * ----------------------------------------------------------------------------
 *
 *                      Getters and setters
 *
 * ----------------------------------------------------------------------------
 */

/* ---------------------------------------------------------------------------
 *
 *                              Methods
 *
 * ---------------------------------------------------------------------------
 */

/**
 *  @brief Setup the request handler.
 */
void RequestHandlerBase::Setup()
{
    _queueHandle = xQueueCreate(MAX_QUEUE_LENGTH, sizeof(Message *));
    if (_queueHandle == NULL)
    {
        ERROR_MESSAGE("Cannot allocate ESP32 handler queue.");
    }
}

/**
 *  @brief Process any messages for the controller.
 *
 *  The messages will be generated by the incoming SPI task.
 *
 *  @param pvParameters
 *      Pointer to the instance of the request handler receiving the
 *      messages for dispatch through the instance specific handler.
 */
void RequestHandlerBase::Task(void *pvParameters)
{
    RequestHandlerBase *sender = static_cast<RequestHandlerBase *>(pvParameters);
    while (true)
    {
        Message *message;
        BaseType_t result = xQueueReceive(sender->_queueHandle, &message, portMAX_DELAY);
        if (result == pdTRUE)
        {
            sender->DispatchRequest(message);
        }
    }
    //
    //  We should only get here if the code in the while loop generates a fault.
    //  The documentation for FreeRTOS states that we should delete the task
    //  should we get here.
    //
    vTaskDelete(sender->_taskHandle);
}

/**
 *  @brief Add an incoming message to the queue of messages waiting to be processed.
 *
 *  @param message
 *      Message from the STM32 that needs to be queued.
 *
 *  @return
 *      true if the message could be queued, false if there was a problem.
 */
bool RequestHandlerBase::QueueEsp32Message(Message *message)
{
    bool result = true;
    Logging::DumpMessage(COMPONENT_NAME, message);
    if (xQueueSendToBack(_queueHandle, &message, 0) != pdPASS)
    {
        Message::DeleteMessage(message);
        result = false;
    }

    return(result);
}

/**
 *  @brief Create a new interrupt message and add it to the outbound message queue.
 *
 *  @param interface
 *      Interface to sent the event to.
 *
 *  @param eventType
 *      Type of event being raised.
 *
 *  @param statusCode
 *      Status code.
 *
 *  @param payload
 *      Event payload.
 *
 *  @param payloadLength
 *      Amount of data in the payload.
 */
void RequestHandlerBase::RaiseEvent(uint8_t interface, uint32_t eventType, uint32_t statusCode, uint8_t *payload, uint32_t payloadLength)
{
    TRACE_MESSAGE("Raising event %s", Logging::FunctionName(interface, eventType));
    Message *message = Message::CreateOnHeap(MessageTypes::Event, interface, eventType, statusCode, _messageDispatcher->GetNextMessageID(), payload, payloadLength);
    _messageDispatcher->QueueMessageForStm32(message);
}

/**
 *  @brief Create a new interrupt message and add it to the outbound message queue.
 *
 *  @param interface
 *      Interface to sent the event to.
 *
 *  @param eventType
 *      Type of event being raised.
 *
 *  @param statusCode
 *      Status code.
 */
void RequestHandlerBase::RaiseEvent(uint8_t interface, uint32_t eventType, uint32_t statusCode)
{
    RaiseEvent(interface, eventType, statusCode, nullptr, 0);
}

/**
 *  @brief Create a new interrupt message and add it to the outbound message queue.
 *
 *  @param interface
 *      Interface to sent the event to.
 *
 *  @param eventType
 *      Type of event being raised.
 */
void RequestHandlerBase::RaiseEvent(uint8_t interface, uint32_t eventType)
{
    RaiseEvent(interface, eventType, StatusCodes::CompletedOk, nullptr, 0);
}
