#!/usr/bin/env python3
"""
PEM to DER header converter for mbedTLS root CA loading.

- Reads one or more input files (PEM bundle(s), single PEM, or DER files) and/or directories.
- Extracts all X.509 certificates (PEM blocks labeled CERTIFICATE) and base64-decodes to DER.
- Emits a C header with const unsigned char arrays for each DER cert, plus pointer and length tables.
- Intended to be used with mbedtls_x509_crt_parse_der_nocopy for faster boot.

Usage examples:
  # From a single PEM bundle -> header
  tools/pem_to_der_header.py root-ca-bundle.pem -o mono/mono/mbedtls/root-ca-der.h --prefix root_ca_der

  # From multiple inputs (mix files/dirs)
  tools/pem_to_der_header.py certs/ extras.pem -o root-ca-der.h

Integration (C):
  #include "root-ca-der.h"
  mbedtls_x509_crt cacert; mbedtls_x509_crt_init(&cacert);
  for (size_t i = 0; i < ROOT_CA_DER_COUNT; ++i) {
      int ret = mbedtls_x509_crt_parse_der_nocopy(&cacert, ROOT_CA_DER_LIST[i], ROOT_CA_DER_LEN[i]);
      if (ret != 0) { /* handle error */ }
  }
  mbedtls_ssl_conf_ca_chain(&conf, &cacert, NULL);

Notes:
- PEM certificates are converted by stripping header/footer and base64-decoding the body.
- DER inputs are passed through as-is.
- Non-certificate PEM blocks are ignored.
"""

import argparse
import base64
import re
import sys
from pathlib import Path
from typing import Iterable, List

PEM_CERT_RE = re.compile(
    r"-----BEGIN CERTIFICATE-----\s*(.*?)\s*-----END CERTIFICATE-----",
    re.DOTALL | re.IGNORECASE,
)

# Simple check for DER ASN.1 SEQUENCE tag (0x30) as first byte
# Not bulletproof, but good enough to differentiate typical DER vs. PEM text.

def _looks_like_der(data: bytes) -> bool:
    return len(data) > 2 and data[0] == 0x30


def _extract_der_from_pem_text(text: str) -> List[bytes]:
    ders: List[bytes] = []
    for m in PEM_CERT_RE.finditer(text):
        b64 = m.group(1)
        try:
            der = base64.b64decode(b64.encode("ascii"), validate=False)
        except Exception as ex:
            raise ValueError(f"Failed to decode PEM block: {ex}")
        if not _looks_like_der(der):
            # Still accept, but warn via stderr
            print("Warning: decoded cert does not look like DER SEQUENCE; including anyway.", file=sys.stderr)
        ders.append(der)
    return ders


def _gather_certs_from_path(p: Path) -> List[bytes]:
    ders: List[bytes] = []
    if p.is_dir():
        # Recurse and collect common cert file extensions
        for child in sorted(p.rglob("*")):
            if child.is_file() and child.suffix.lower() in {".pem", ".crt", ".cer", ".der"}:
                ders.extend(_gather_certs_from_path(child))
        return ders

    # File case
    data = p.read_bytes()
    # Heuristic: if it contains PEM header, parse PEM; otherwise treat as DER
    if b"-----BEGIN CERTIFICATE-----" in data:
        text = data.decode("utf-8", errors="ignore")
        ders.extend(_extract_der_from_pem_text(text))
    else:
        # Assume DER
        if not _looks_like_der(data):
            print(f"Warning: {p} does not look like DER; including as-is.", file=sys.stderr)
        ders.append(data)
    return ders


def _c_bytes_literal(b: bytes, indent: str = "    ", per_line: int = 16) -> str:
    # Format as comma-separated 0xNN with wrapping
    hexes = [f"0x{byte:02x}" for byte in b]
    lines = []
    for i in range(0, len(hexes), per_line):
        lines.append(indent + ", ".join(hexes[i : i + per_line]))
    return ",\n".join(lines)


def _macroize(name: str) -> str:
    out = re.sub(r"[^A-Za-z0-9]", "_", name).upper()
    out = re.sub(r"__+", "_", out)
    return out.strip("_")


def generate_header(
    ders: List[bytes],
    prefix: str,
    header_guard: str,
    list_name: str,
    len_name: str,
    count_name: str,
    public: bool,
) -> str:
    if not ders:
        raise SystemExit("No certificates found in input. Nothing to do.")

    storage = "" if public else "static "

    lines: List[str] = []
    lines.append("/* Auto-generated by pem_to_der_header.py; DO NOT EDIT. */")
    lines.append(f"#ifndef {header_guard}")
    lines.append(f"#define {header_guard}")
    lines.append("")
    lines.append("#include <stddef.h>")
    lines.append("#include <stdint.h>")
    lines.append("")

    # Emit each cert as a const unsigned char array
    for idx, der in enumerate(ders):
        lines.append(f"/* cert #{idx}, {len(der)} bytes */")
        lines.append(f"{storage}const unsigned char {prefix}_cert_{idx}[] = {{")
        lines.append(_c_bytes_literal(der))
        lines.append("};")
        lines.append("")

    # Emit pointer table
    lines.append(f"{storage}const unsigned char* {list_name}[] = {{")
    if ders:
        for idx in range(len(ders)):
            lines.append(f"    {prefix}_cert_{idx},")
    lines.append("};")
    lines.append("")

    # Emit length table
    lines.append(f"{storage}const size_t {len_name}[] = {{")
    if ders:
        for idx, der in enumerate(ders):
            lines.append(f"    {len(der)},")
    lines.append("};")
    lines.append("")

    # Emit count
    lines.append(f"{storage}const size_t {count_name} = {len(ders)};")
    lines.append("")
    lines.append(f"#endif /* {header_guard} */")

    return "\n".join(lines) + "\n"


def main(argv: Iterable[str]) -> int:
    ap = argparse.ArgumentParser(description="Convert PEM/DER X.509 certs to a C header of DER arrays.")
    ap.add_argument("inputs", nargs="+", help="Input file(s) or directory/ies containing PEM/DER certs")
    ap.add_argument("-o", "--output", help="Output header path (default: stdout)")
    ap.add_argument("--prefix", default="root_ca_der", help="Prefix for generated arrays (default: root_ca_der)")
    ap.add_argument("--guard", default=None, help="Custom header guard macro (default derived from output filename)")
    ap.add_argument("--public-names", action="store_true", help="Use non-static symbols (export tables and arrays)")
    args = ap.parse_args(argv)

    ders: List[bytes] = []
    for inp in args.inputs:
        p = Path(inp)
        if not p.exists():
            print(f"Error: {inp} not found", file=sys.stderr)
            return 2
        ders.extend(_gather_certs_from_path(p))

    if not ders:
        print("No certificates found.", file=sys.stderr)
        return 1

    # Deduplicate identical DER blobs to reduce size (optional but helpful)
    unique_map = {}
    unique_list: List[bytes] = []
    for der in ders:
        key = der  # bytes are hashable
        if key not in unique_map:
            unique_map[key] = len(unique_list)
            unique_list.append(der)
    ders = unique_list

    # Build symbol names
    prefix = args.prefix.strip()
    macro_base = args.guard or (Path(args.output).name if args.output else prefix)
    header_guard = _macroize(macro_base or prefix) + "_H"

    # Table names exported to be friendly and stable
    list_name = _macroize(prefix) + "_LIST"
    len_name = _macroize(prefix) + "_LEN"
    count_name = _macroize(prefix) + "_COUNT"

    header = generate_header(
        ders,
        prefix=prefix,
        header_guard=header_guard,
        list_name=list_name,
        len_name=len_name,
        count_name=count_name,
        public=args.public_names,
    )

    if args.output:
        out_path = Path(args.output)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(header)
        print(f"Wrote {len(ders)} cert(s) to {out_path}")
    else:
        sys.stdout.write(header)

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
